[package]
name = "debug_server"
version = "1.0.1"
authors = ["William Wallace <me@wiox.me>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.0"

[dependencies]
auxtools = { path = "../auxtools" }
lazy_static = "1.4.0"
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.1"
clap = "2.33.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "libloaderapi"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dependencies.detour]
version = "0.7"
default-features = false
